#pragma once

enum GameLayerIndex
{
	LAYERINDEX_GROUND =				0,
	LAYERINDEX_PLATFORM =			1,
	LAYERINDEX_DOOR =				2,
	LAYERINDEX_GROUND_OBJECT =		3,

	LAYERINDEX_BREAKABLE_PLATFORM = 6,

	LAYERINDEX_TRIGGER =			14,
	LAYERINDEX_CHARACTER =			15,
};

enum GameLayer
{
	LAYER_GROUND =					1 << LAYERINDEX_GROUND,
	LAYER_PLATFORM =				1 << LAYERINDEX_PLATFORM,
	LAYER_DOOR =					1 << LAYERINDEX_DOOR,
	LAYER_GROUND_OBJECT =			1 << LAYERINDEX_GROUND_OBJECT,

	LAYER_BREAKABLE_PLATFORM =		1 << LAYERINDEX_BREAKABLE_PLATFORM,

	LAYER_TRIGGER =					1 << LAYERINDEX_TRIGGER,
	LAYER_CHARACTER =				1 << LAYERINDEX_CHARACTER,
};