#pragma once

enum CoreExecutionOrder
{
	BEFORE_FIXED_STEP_ORDER_BODY =		INT_MIN,
	FIXED_UPDATE_ORDER_BODY =			INT_MIN,
	LATE_FIXED_UPDATE_ORDER_BODY =		INT_MAX,
	UPDATE_ORDER_BODY =					INT_MIN,
	LATE_UPDATE_ORDER_BODY =			INT_MAX,
	AFTER_UPDATE_ORDER_BODY =			INT_MAX,

	FIXED_UPDATE_ORDER_COLLIDER =		INT_MAX,
	UPDATE_ORDER_COLLIDER =				INT_MAX,
	LATE_UPDATE_ORDER_COLLIDER =		INT_MAX,

	BEFORE_RENDER_ORDER_CAMREA =		INT_MAX,
};